h_p_data_ordenada = [
    # Nivel 1: Muerte o daño severo inmediato
    ("H300+H310+H330", "Fatal si se ingiere, en contacto con la piel o si se inhala",1),
    ("H300+H330", "Fatal si se ingiere o si se inhala",2),
    ("H310+H330", "Fatal en contacto con la piel o si se inhala",3),
    ("H300+H310", "Fatal si se ingiere o en contacto con la piel",4),
    ("H300", "Fatal si se ingiere",5),
    ("H310", "Fatal en contacto con la piel",6),
    ("H330", "Fatal si se inhala",7),
    ("H301+H311+H331", "Tóxico si se ingiere, en contacto con la piel o si se inhala",8),
    ("H301+H331", "Tóxico si se ingiere o si se inhala",9),
    ("H301+H311", "Tóxico si se ingiere o en contacto con la piel",10),
    ("H301", "Tóxico si se ingiere",11),
    ("H311+H331", "Tóxico en contacto con la piel o si se inhala",12),
    ("H311", "Tóxico en contacto con la piel",13),
    ("H331", "Tóxico si se inhala",14),
    ("H304", "Puede ser fatal si se ingiere y entra en las vías respiratorias",15),

    # Nivel 2: Explosivos, inflamables extremos, presión
    ("H200", "Explosivo inestable",16),
    ("H201", "Explosivo: peligro de explosión masiva",17),
    ("H202", "Explosivo: peligro grave de proyección",18),
    ("H203", "Explosivo: peligro de incendio, explosión o proyección",19),
    ("H204", "Peligro de incendio o proyección",20),
    ("H205", "Puede explotar masivamente en un incendio",21),
    ("H206", "Mayor riesgo de explosión si se reduce el agente desensibilizante",22),
    ("H207", "Peligro de incendio o proyección con desensibilizante reducido",23),
    ("H208", "Peligro de incendio si se reduce el agente desensibilizante",24),
    ("H230", "Reacción explosiva sin aire",25),
    ("H231", "Reacción explosiva sin aire a alta presión o temperatura",26),
    ("H240", "El calentamiento puede causar una explosión",27),
    ("H241", "El calentamiento puede causar un incendio o explosión",28),
    ("H250", "Se prende fuego espontáneamente al aire",29),
    ("H251", "Autocalentamiento: puede prenderse fuego",30),
    ("H260", "Con agua libera gases inflamables que pueden encenderse",31),
    ("H271", "Puede causar incendio o explosión: oxidante fuerte",32),
    ("H282", "Químico extremadamente inflamable a presión: puede explotar",33),

    # Nivel 3: Cáncer, mutaciones, fertilidad
    ("H340", "Puede causar defectos genéticos",34),
    ("H341", "Se sospecha que causa defectos genéticos",35),
    ("H350", "Puede causar cáncer",36),
    ("H350i", "Puede causar cáncer por inhalación",37),
    ("H351", "Se sospecha que causa cáncer",38),
    ("H360", "Puede dañar la fertilidad o al feto",39),
    ("H360D", "Puede dañar al feto",40),
    ("H360F", "Puede dañar la fertilidad",41),
    ("H360FD", "Puede dañar la fertilidad y al feto",42),
    ("H360Fd", "Puede dañar la fertilidad. Se sospecha que daña al feto.",43),
    ("H360Df", "Puede dañar al feto. Se sospecha que daña la fertilidad.",44),
    ("H361", "Se sospecha que daña la fertilidad o al feto",45),
    ("H361d", "Se sospecha que daña al feto",46),
    ("H361f", "Se sospecha que daña la fertilidad",47),
    ("H361fd", "Se sospecha que daña la fertilidad y al feto",48),
    ("H362", "Puede causar daño a los niños amamantados",85),

    # Nivel 4: Daño a órganos
    ("H370", "Causa daño a los órganos",49),
    ("H371", "Puede causar daño a los órganos",50),
    ("H372", "Causa daño a los órganos por exposición prolongada o repetida",51),
    ("H373", "Puede causar daño a los órganos por exposición prolongada o repetida",52),

    # Nivel 5: Inflamables, corrosivos, irritantes
    ("H220", "Gas extremadamente inflamable",53),
    ("H222", "Material extremadamente inflamable",54),
    ("H224", "Líquido y vapor extremadamente inflamables",55),
    ("H225", "Líquido y vapor altamente inflamables",56),
    ("H226", "Líquido y vapor inflamables",57),
    ("H228", "Sólido inflamable",58),
    ("H229", "Envase a presión: puede estallar si se calienta",59),
    ("H270", "Puede causar o intensificar el fuego: oxidante",60),
    ("H272", "Puede intensificar el fuego: oxidante",61),
    ("H232", "Puede encenderse espontáneamente al aire",62),
    ("H314", "Causa quemaduras graves en la piel y daño ocular",63),
    ("H317", "Puede causar una reacción alérgica en la piel",64),
    ("H334", "Puede causar síntomas de alergia o asma si se inhala",65),
    ("H335", "Puede causar irritación respiratoria",66),
    ("H336", "Puede causar somnolencia o mareos",67),
    ("H318", "Causa daño grave en los ojos",68),
    ("H319", "Causa irritación grave en los ojos",69),

    # Nivel 6: Riesgos menores, ambientales
    ("H302", "Nocivo si se ingiere",70),
    ("H312", "Nocivo en contacto con la piel",71),
    ("H332", "Nocivo si se inhala",72),
    ("H303", "Puede ser nocivo si se ingiere",73),
    ("H313", "Puede ser nocivo en contacto con la piel",74),
    ("H333", "Puede ser nocivo si se inhala",75),
    ("H315", "Causa irritación en la piel",76),
    ("H316", "Causa irritación leve en la piel",77),
    ("H320", "Causa irritación ocular",78),
    ("H401", "Tóxico para la vida acuática",79),
    ("H411", "Tóxico para la vida acuática con efectos duraderos",80),
    ("H412", "Nocivo para la vida acuática con efectos duraderos",81),
    ("H413", "Puede causar efectos nocivos duraderos para la vida acuática",82),
    ("H420", "Daña la salud pública destruyendo ozono",83),
    ("H290", "Puede ser corrosivo para los metales",84),
]
