h_p_data_lista = [
    ("H200", "Explosivo inestable"),
    ("H201", "Explosivo: peligro de explosión masiva"),
    ("H202", "Explosivo: peligro grave de proyección"),
    ("H203", "Explosivo: peligro de incendio, explosión o proyección"),
    ("H204", "Peligro de incendio o proyección"),
    ("H205", "Puede explotar masivamente en un incendio"),
    ("H206", "Peligro de incendio, explosión o proyección: mayor riesgo de explosión si se reduce el agente desensibilizante"),
    ("H207", "Peligro de incendio o proyección; mayor riesgo de explosión si se reduce el agente desensibilizante"),
    ("H208", "Peligro de incendio; mayor riesgo de explosión si se reduce el agente desensibilizante"),
    ("H209", "Explosivo"),
    ("H210", "Muy sensible"),
    ("H211", "Puede ser sensible"),
    ("H220", "Gas extremadamente inflamable"),
    ("H221", "Gas inflamable"),
    ("H222", "Material extremadamente inflamable"),
    ("H223", "Material inflamable"),
    ("H224", "Líquido y vapor extremadamente inflamables"),
    ("H225", "Líquido y vapor altamente inflamables"),
    ("H226", "Líquido y vapor inflamables"),
    ("H227", "Líquido combustible"),
    ("H228", "Sólido inflamable"),
    ("H229", "Envase a presión: puede estallar si se calienta"),
    ("H230", "Puede reaccionar explosivamente incluso en ausencia de aire"),
    ("H231", "Puede reaccionar explosivamente incluso en ausencia de aire a alta presión y/o temperatura"),
    ("H232", "Puede encenderse espontáneamente si se expone al aire"),
    ("H240", "El calentamiento puede causar una explosión"),
    ("H241", "El calentamiento puede causar un incendio o explosión"),
    ("H242", "El calentamiento puede causar un incendio"),
    ("H250", "Se prende fuego espontáneamente si se expone al aire"),
    ("H251", "Autocalentamiento: puede prenderse fuego"),
    ("H252", "Autocalentamiento en grandes cantidades: puede prenderse fuego"),
    ("H260", "En contacto con agua libera gases inflamables que pueden encenderse espontáneamente"),
    ("H261", "En contacto con agua libera gas inflamable"),
    ("H270", "Puede causar o intensificar el fuego: oxidante"),
    ("H271", "Puede causar incendio o explosión: oxidante fuerte"),
    ("H272", "Puede intensificar el fuego: oxidante"),
    ("H280", "Contiene gas a presión: puede explotar si se calienta"),
    ("H281", "Contiene gas refrigerado: puede causar quemaduras criogénicas o lesiones"),
    ("H282", "Producto químico extremadamente inflamable a presión: puede explotar si se calienta"),
    ("H283", "Producto químico inflamable a presión: puede explotar si se calienta"),
    ("H284", "Producto químico a presión: puede explotar si se calienta"),
    ("H290", "Puede ser corrosivo para los metales"),
    ("H300", "Fatal si se ingiere"),
    ("H300+H310", "Fatal si se ingiere o en contacto con la piel"),
    ("H300+H310+H330", "Fatal si se ingiere, en contacto con la piel o si se inhala"),
    ("H300+H330", "Fatal si se ingiere o si se inhala"),
    ("H301", "Tóxico si se ingiere"),
    ("H301+H311", "Tóxico si se ingiere o en contacto con la piel"),
    ("H301+H311+H331", "Tóxico si se ingiere, en contacto con la piel o si se inhala"),
    ("H301+H331", "Tóxico si se ingiere o si se inhala"),
    ("H302", "Nocivo si se ingiere"),
    ("H302+H312", "Nocivo si se ingiere o en contacto con la piel"),
    ("H302+H312+H332", "Nocivo si se ingiere, en contacto con la piel o si se inhala"),
    ("H302+H332", "Nocivo si se ingiere o si se inhala"),
    ("H303", "Puede ser nocivo si se ingiere"),
    ("H303+H313", "Puede ser nocivo si se ingiere o en contacto con la piel"),
    ("H303+H313+H333", "Puede ser nocivo si se ingiere, en contacto con la piel o si se inhala"),
    ("H303+H333", "Puede ser nocivo si se ingiere o si se inhala"),
    ("H304", "Puede ser fatal si se ingiere y entra en las vías respiratorias"),
    ("H305", "Puede ser nocivo si se ingiere y entra en las vías respiratorias"),
    ("H310", "Fatal en contacto con la piel"),
    ("H310+H330", "Fatal en contacto con la piel o si se inhala"),
    ("H311", "Tóxico en contacto con la piel"),
    ("H311+H331", "Tóxico en contacto con la piel o si se inhala"),
    ("H312", "Nocivo en contacto con la piel"),
    ("H312+H332", "Nocivo en contacto con la piel o si se inhala"),
    ("H313", "Puede ser nocivo en contacto con la piel"),
    ("H313+H333", "Puede ser nocivo en contacto con la piel o si se inhala"),
    ("H314", "Causa quemaduras graves en la piel y daño ocular"),
    ("H315", "Causa irritación en la piel"),
    ("H315+H320", "Causa irritación en la piel y los ojos"),
    ("H316", "Causa irritación leve en la piel"),
    ("H317", "Puede causar una reacción alérgica en la piel"),
    ("H318", "Causa daño grave en los ojos"),
    ("H319", "Causa irritación grave en los ojos"),
    ("H320", "Causa irritación ocular"),
    ("H330", "Fatal si se inhala"),
    ("H331", "Tóxico si se inhala"),
    ("H332", "Nocivo si se inhala"),
    ("H333", "Puede ser nocivo si se inhala"),
    ("H334", "Puede causar síntomas de alergia o asma o dificultades respiratorias si se inhala"),
    ("H335", "Puede causar irritación respiratoria"),
    ("H336", "Puede causar somnolencia o mareos"),
    ("H340", "Puede causar defectos genéticos"),
    ("H341", "Se sospecha que causa defectos genéticos"),
    ("H350", "Puede causar cáncer"),
    ("H350i", "Puede causar cáncer por inhalación"),
    ("H351", "Se sospecha que causa cáncer"),
    ("H360", "Puede dañar la fertilidad o al feto"),
    ("H360D", "Puede dañar al feto"),
    ("H360Df", "Puede dañar al feto. Se sospecha que daña la fertilidad."),
    ("H360F", "Puede dañar la fertilidad"),
    ("H360FD", "Puede dañar la fertilidad. Puede dañar al feto."),
    ("H360Fd", "Puede dañar la fertilidad. Se sospecha que daña al feto."),
    ("H361", "Se sospecha que daña la fertilidad o al feto"),
    ("H361d", "Se sospecha que daña al feto"),
    ("H361f", "Se sospecha que daña la fertilidad"),
    ("H361fd", "Se sospecha que daña la fertilidad. Se sospecha que daña al feto."),
    ("H362", "Puede causar daño a los niños amamantados"),
    ("H370", "Causa daño a los órganos"),
    ("H371", "Puede causar daño a los órganos"),
    ("H372", "Causa daño a los órganos por exposición prolongada o repetida"),
    ("H373", "Puede causar daño a los órganos por exposición prolongada o repetida"),
    ("H400", "Muy tóxico para la vida acuática"),
    ("H401", "Tóxico para la vida acuática"),
    ("H402", "Nocivo para la vida acuática"),
    ("H410", "Muy tóxico para la vida acuática con efectos duraderos"),
    ("H411", "Tóxico para la vida acuática con efectos duraderos"),
    ("H412", "Nocivo para la vida acuática con efectos duraderos"),
    ("H413", "Puede causar efectos nocivos duraderos para la vida acuática"),
    ("H420", "Daña la salud pública y el medio ambiente destruyendo el ozono en la atmósfera superior"),
    ("H441", "Muy tóxico para los invertebrados terrestres")
]
