services:
  - type: web
    name: ocr-fastapi-app          
    env: docker
    plan: free                     
    dockerfilePath: ./Dockerfile   
    buildCommand: ""               
    startCommand: "./start.sh"     
    autoDeploy: true               
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
